/* StatCommand.h
 * Copyright by Beyondy.c.w 2002-2020
**/
#ifndef __STAT_COMMAND__H
#define __STAT_COMMAND__H

enum {
	CMD_STAT_AGENT_REPORT_HOSTINFO_REQ = 0,
	CMD_STAT_AGENT_REPORT_HOSTINFO_RSP,

	CMD_STAT_AGENT_GET_STORAGE_DISTRIBUTION_REQ,
	CMD_STAT_AGENT_GET_STORAGE_DISTRIBUTION_RSP,

	CMD_STAT_AGENT_SAVE_STATS_REQ,
	CMD_STAT_AGENT_SAVE_STATS_RSP,

	CMD_STAT_GET_SYSTEM_STATS_REQ,
	CMD_STAT_GET_SYSTEM_STATS_RSP,

	CMD_STAT_GET_USER_STATS_REQ,
	CMD_STAT_GET_USER_STATS_RSP,

	CMD_BUTT
};

#endif /* __STAT_COMMAND__H */
