#ifndef __STAT_ERROR_NO__H
#define __STAT_ERROR_NO__H

enum {
	E_STAT_DATA_PARSE_GAUGE_NOT_ENOUGH,
	E_STAT_DATA_ENCODE_GAUGE_NOT_ENOUGH,
	E_STAT_DATA_ITEM_LCALL_PARSE_FAILED,
	E_STAT_DATA_ITEM_LCALL_ENCODE_FAILED,
	E_STAT_DATA_MERGED_LCALL_PARSE_FAILED,
	E_STAT_DATA_MERGED_LCALL_ENCODE_FAILED,
	E_STAT_DATA_ITEM_RCALL_PARSE_FAILED,
	E_STAT_DATA_ITEM_RCALL_ENCODE_FAILED,
	E_STAT_DATA_MERGED_RCALL_PARSE_FAILED,
	E_STAT_DATA_MERGED_RCALL_ENCODE_FAILED,

	E_STAT_AGENT_CLIENT_OPEN,
	E_STAT_AGENT_CLIENT_WRITE_ERROR,
	E_STAT_AGENT_CLIENT_WRITE_PARTIAL,

	E_STAT_PARAMETER_MISSING,
	E_STAT_PROTOCOL_CORRUPTED,
	E_STAT_GET_SYSTEM_STATS_FAILED,
	E_STAT_OOM,
	E_STAT_ENCODE_FAILED,

	E_BUTT
};

#endif /* __STAT_ERROR_NO__H */
